function (wsjt_read_release_state state_file version_out channel_out rc_out revision_out)
  if (NOT EXISTS "${state_file}")
    message (FATAL_ERROR "Release state file not found: ${state_file}")
  endif ()

  file (STRINGS "${state_file}" _wsjt_release_state_lines ENCODING UTF-8)
  list (LENGTH _wsjt_release_state_lines _wsjt_release_state_line_count)
  if (NOT _wsjt_release_state_line_count EQUAL 4
      AND NOT _wsjt_release_state_line_count EQUAL 5)
    message (FATAL_ERROR "${state_file} must contain four or five metadata lines")
  endif ()

  set (_wsjt_release_state_keys version channel rc revision)
  set (_wsjt_release_state_allowed_keys ${_wsjt_release_state_keys} windows_signing)
  foreach (_wsjt_release_state_line IN LISTS _wsjt_release_state_lines)
    if (NOT _wsjt_release_state_line MATCHES "^([a-z_]+)=(.*)$")
      message (FATAL_ERROR "Invalid release metadata line: ${_wsjt_release_state_line}")
    endif ()

    set (_wsjt_release_state_key "${CMAKE_MATCH_1}")
    set (_wsjt_release_state_value "${CMAKE_MATCH_2}")
    if (NOT _wsjt_release_state_key IN_LIST _wsjt_release_state_allowed_keys)
      message (FATAL_ERROR "Unknown release metadata key: ${_wsjt_release_state_key}")
    endif ()
    if (DEFINED _wsjt_release_state_${_wsjt_release_state_key})
      message (FATAL_ERROR "Duplicate release metadata key: ${_wsjt_release_state_key}")
    endif ()
    set (_wsjt_release_state_${_wsjt_release_state_key} "${_wsjt_release_state_value}")
  endforeach ()

  if (DEFINED _wsjt_release_state_windows_signing
      AND NOT _wsjt_release_state_windows_signing MATCHES "^(signpath|unsigned)$")
    message (FATAL_ERROR "Windows signing mode must be signpath or unsigned")
  endif ()

  foreach (_wsjt_release_state_key IN LISTS _wsjt_release_state_keys)
    if (NOT DEFINED _wsjt_release_state_${_wsjt_release_state_key})
      message (FATAL_ERROR "Missing release metadata key: ${_wsjt_release_state_key}")
    endif ()
  endforeach ()

  if (NOT _wsjt_release_state_version MATCHES "^[0-9]+[.][0-9]+[.][0-9]+$")
    message (FATAL_ERROR "Release version must have the form X.Y.Z")
  endif ()
  if (NOT _wsjt_release_state_channel MATCHES "^(DEVEL|RC|GA)$")
    message (FATAL_ERROR "Release channel must be DEVEL, RC, or GA")
  endif ()
  if (_wsjt_release_state_channel STREQUAL "RC")
    if (NOT _wsjt_release_state_rc MATCHES "^[1-9][0-9]*$")
      message (FATAL_ERROR "RC release state requires a positive rc number")
    endif ()
  elseif (NOT _wsjt_release_state_rc STREQUAL "")
    message (FATAL_ERROR "The rc value must be empty for DEVEL and GA release states")
  endif ()

  if (NOT _wsjt_release_state_revision STREQUAL "$Format:%H$")
    string (LENGTH "${_wsjt_release_state_revision}" _wsjt_release_state_revision_length)
    if (NOT _wsjt_release_state_revision MATCHES "^[0-9a-fA-F]+$"
        OR (NOT _wsjt_release_state_revision_length EQUAL 40
            AND NOT _wsjt_release_state_revision_length EQUAL 64))
      message (FATAL_ERROR "Archive revision must be a full Git object ID")
    endif ()
  endif ()

  set (${version_out} "${_wsjt_release_state_version}" PARENT_SCOPE)
  set (${channel_out} "${_wsjt_release_state_channel}" PARENT_SCOPE)
  set (${rc_out} "${_wsjt_release_state_rc}" PARENT_SCOPE)
  if (_wsjt_release_state_revision STREQUAL "$Format:%H$")
    set (${revision_out} "" PARENT_SCOPE)
  else ()
    string (TOLOWER "${_wsjt_release_state_revision}" _wsjt_release_state_revision)
    set (${revision_out} "${_wsjt_release_state_revision}" PARENT_SCOPE)
  endif ()
endfunction ()

function (wsjt_set_source_default_cache variable source_default description)
  set (_previous_default "_WSJT_PREVIOUS_SOURCE_DEFAULT_${variable}")
  if (NOT DEFINED ${variable})
    set (${variable} "${source_default}" CACHE STRING "${description}" FORCE)
  elseif (DEFINED ${_previous_default}
      AND "${${variable}}" STREQUAL "${${_previous_default}}")
    set (${variable} "${source_default}" CACHE STRING "${description}" FORCE)
  endif ()
  set (${_previous_default} "${source_default}" CACHE INTERNAL "Previous source default for ${variable}" FORCE)
endfunction ()
